<?php require_once './templates/header.phtml' ?>

<form method='POST' action='book-edited/<?= $book->libroId ?>'>
    <div class="form-group">
      <label for="nombreLibro">Nombre</label>
      <input type="text" class="form-control" id="nombreLibro" name='nombreLibro' placeholder="Nombre del libro" value='<?= $book->nombreLibro ?>'>
    </div>
    <div class="form-group">
      <label for="fechaLanzamiento">Nombre</label>
      <input type="date" class="form-control" id="fechaLanzamiento" name='fechaLanzamiento' placeholder="Fecha de creación" value='<?= $book->fechaLanzamiento ?>'>
    </div>
    <div class="form-group">
        <label for="autoresId">Autores</label>
        <select class="form-control" name='autoresId' id='autoresId'>
            <?php foreach($devs as $dev): ?>
            <option <?php if($book->autoresId == $dev->autoresId): ?>selected<?php endif ?> value='<?= $dev->autoresId ?>'><?= $dev->nombreAutores ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label for="edad">Edad mínima</label>
        <input type="number" min='0' class="form-control" id="edad" name='edad' placeholder="Edad mínima" value='<?= $book->edad ?>'>
    </div>
    <div class="form-group">
        <label for="descripcionLibro">Descripción del libro</label>
        <textarea class="form-control" id="descripcionLibro" name='descripcionLibro' placeholder="Descripción del Libro"><?= $book->descripcionLibro ?></textarea>
    </div><div class="form-group">
        <label for="imagen">Imagen</label>
        <input type="text" class="form-control" id="imagen" name='imagen' value='<?= $book->imagen ?>' placeholder="Inserte el link de la imagen">
    </div>
    <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './templates/footer.phtml' ?>